### ISSUE TITLE
Arguments not identified at all (cc3200/toniebox)

### ISSUE THREAD

**Issue by SciLor** [spacehuhn/SimpleCLI#10]
I am currently try to use your lib on one of my projects.

First of all:
I am using it on a ti cc3200 (toniebox) with energia (arduino fork).

But it doesn't seem to be able to read my input. (I am sending it as string over the parse interface).

Definition
```
    cmdI2C = cli.addCmd("i2c");
    cmdI2C.setDescription("Access I2C");
    cmdI2C.addFlagArg("r/ead");
    cmdI2C.addFlagArg("w/rite");
    cmdI2C.addArg("a/ddress");
    cmdI2C.addArg("r/egister");
    cmdI2C.addArg("v/alue", "");
    cmdI2C.addArg("l/ength", "");
    cmdI2C.addArg("o/utput", "b");

    cmdHelp = cli.addCmd("h/elp");
    cmdHelp.setDescription("Get help!");
```
Input
`i2c read -address 0x10 -register 0b10000000`

Output
```
ERROR: Unknown argument at command 'i2c' at 'read'
Did you mean "i2c [-r/ead] [-w/rite] -a/ddress <value> -r/egister <value> [-v/alue <value>] [-l/ength <value>] [-o/utput <b>]
Access I2C"?

```

Full code:
https://github.com/toniebox-reverse-engineering/hackiebox_cfw/blob/develop/BoxCLI.cpp

**Comment by spacehuhn** [comment]
Hi, shouldn't it be `i2c -read -address 0x10 -register 0b10000000`? There is  a `-` missing before `read`.

**Comment by SciLor** [comment]
*facepalm*
Thanks for the hint.
