### ISSUE TITLE
Method Misspelled: setCaseSensetive -> setCaseSensitive

### ISSUE THREAD

**Issue by MattStarfield** [spacehuhn/SimpleCLI#14]
Suggestion to correct the misspelling of the method `setCaseSensetive ` to `setCaseSensitive`

Since correcting this misspelling will break compatibility with code using the original spelling, maybe create an addition method `setCaseSensitive` that simply calls the original method (or vice versa)

**Comment by spacehuhn** [comment]
Oh wow thanks I would have never found this typo.
