### ISSUE TITLE
Arduino blocks after multiple CLI calls

### ISSUE THREAD

**Issue by andikt** [spacehuhn/SimpleCLI#2]
Hi spacehuhn, 

Thanks a lot for sharing this nice cli function lib. I use the SimpleCLI on an Arduino Mega2560 and my implementation works very well. 

But what i recognize is, that after 300-500 hundred parsed command lines (slightly depending on which command i send), the Arduino get stuck and is not reacting any more. After a reset, it works fine again, until the same number of commands are parsed again. When i do a direct call to the callback functions as a workaround without using the .parse() function, everything works stable for hours. 

So my guess is, that there might be a memory overflow issue within your parser function. 
Could you please check? 

Thanks a lot and best regards, 

Andi

**Comment by spacehuhn** [comment]
Can you share your code or provide a similar example to recreate the bug?

**Comment by andikt** [comment]
Sure, here you go: 

`
#include <Arduino.h>
#include <SimpleCLI.h>
#include "DS_EEProm_New.h"
#include <Wire.h>
#include <Adafruit_MCP23017.h>
#include <TMC2130.h>

#include "globals.h"

// Callback functions
// ... 

void ButtonsCallback(cmd* cmdPtr) {
  Command cmd(cmdPtr);
  Argument argF = cmd.getArgument("a");
  bool PassButton = true;
  bool FailButton = true;
  if( cmd.getArgument("p").isSet() ) FailButton = false;
  else if ( cmd.getArgument("f").isSet() ) PassButton = false;
  if(PassButton) {
    if( digitalRead(PASSBUTTON) == 0 )Serial.println("Pass button: Off ");
    else Serial.println("Pass button: On ");
  }
  if(FailButton) {
    if( digitalRead(FAILBUTTON) == 0 )Serial.println("Fail button: Off");
    else Serial.println("Fail button: On");
  }
  Serial.println("ok");
}

void DUTStatesCallback(cmd* cmdPtr) {
  Command cmd(cmdPtr);

  if( digitalRead(DUTPRESENT) == 1 )Serial.println("DUT Present: true");
  else Serial.println("DUT Present: false");
  if( digitalRead(DUTCONNECTED) == 1 )Serial.println("DUT Connected: true");
  else Serial.println("DUT Connected: false");
  if( digitalRead(LOCK_OPEN_SENSE) )Serial.println("DUT Lock open: true");
  else    Serial.println("DUT Lock open: false");
  if( digitalRead(LOCK_CLOSE_SENSE) )Serial.println("DUT Lock close: true");
  else    Serial.println("DUT Lock close: false");
  if( digitalRead(LOWER_END_POS) )Serial.println("Neddles lower position: true");
  else    Serial.println("Neddles lower position: false");
  if( digitalRead(UPPER_END_POS) )Serial.println("Neddles upper position: true");
  else    Serial.println("Neddles upper position: false");
  Serial.println("ok");
}

void SlotIdCallback(cmd* cmdPtr) {
  Command cmd(cmdPtr);
  int i = 
 digitalRead(SLOTID0)+2*digitalRead(SLOTID1)+4*digitalRead(SLOTID2)+8*digitalRead(SLOTID3);
  Serial.print("SlotId: ");
  Serial.println(i);
  Serial.println("ok");
}

void errorCallback(cmd_error* errorPtr) {
    CommandError e(errorPtr);
    Serial.println("ERROR: " + e.toString());

    if (e.hasCommand()) {
        Serial.println("Did you mean? " + e.getCommand().toString());
    } else {
        Serial.println(cli.toString());
    }
}

// .....


////////////////////////////////////////////////////////////////////////////////

void setup() {
 
 Serial.begin(115200);


  pinMode(DUTPRESENT, INPUT_PULLUP);
  pinMode(DUTCONNECTED, INPUT_PULLUP);
  pinMode(LOCK_OPEN_SENSE, INPUT_PULLUP);
  pinMode(LOCK_CLOSE_SENSE, INPUT_PULLUP);
  pinMode(LOWER_END_POS, INPUT_PULLUP);
  pinMode(UPPER_END_POS, INPUT_PULLUP);

// ...

  Buttons = cli.addCmd("b/utt/on/s", ButtonsCallback);
  Buttons.addFlagArgument("a/ll", "a");
  Buttons.addFlagArgument("p/ass", "a");
  Buttons.addFlagArgument("f/ail", "a");

  DUTStates = cli.addCmd("DUTS/tates", DUTStatesCallback);

  Help= cli.addCmd("h/elp", errorCallback);

  SlotId = cli.addCmd("SlotId", SlotIdCallback);

 //... 
 
  cli.setOnError(errorCallback);

  Serial.println("CLI interface started");
  Serial.print("# ");
  Serial.setTimeout(100);

  EmptyString = String();
  St1=EmptyString;
  St2=EmptyString;

}

void loop() {
  // put your main code here, to run repeatedly:
 
  if(Serial.available()) {
    St1 = Serial.readString();

  // Echo the user input
    Serial.print(St1);

    St2 += St1;

    if( St1.indexOf('\r') >= 0 ) {

      cli.parse(St2);

//  Using this code instead of the 'parse' function runs stable for hours: 
 
//      if( St2.indexOf("DUTStates") >=0 ) {
//        DUTStatesCallback(0);
//      }

        Serial.print("# ");
        St1=EmptyString;
        St2=EmptyString;
      }
    }
  }
`

and the globals.h file: 

` 
#ifndef GLOBALS_H
#define GLOBALS_H

// Pin assignments

// Digital Inputs for Slot Id:
#define SLOTID0 22
#define SLOTID1 23
#define SLOTID2 24
#define SLOTID3 25

// Digital Inputs for Buttons:
#define PASSBUTTON 26
#define FAILBUTTON 27

// Digital Inputs for DUT sensors:
#define DUTPRESENT 30
#define DUTCONNECTED 31
#define LOCK_OPEN_SENSE 42
#define LOCK_CLOSE_SENSE 43
#define LOWER_END_POS 40
#define UPPER_END_POS 41


// Create CLI Object
SimpleCLI cli;


// Global Variables
String St1;
String St2;
String EmptyString;


// Commands
Command AdapterId;
Command DUTStates;
Command Buttons;
Command Help;
Command SlotId;
// ... 

#endif
`

For reproducing this behaviour, i ran either the command 'Buttons' or 'DUTStates' repeatedly over the CLI and the Arduino stops communicating after appr. 300 to 400 repetitions. 

Thanks for your support, 

Andi

**Comment by spacehuhn** [comment]
Thanks!

Found the nastly little bug and pushed a fix for it: 1ff85c4c2d7dc9af22daf6982d5dba721264e301

I will make a new release as soon as you confirm that the changes work for you too.

**Comment by andikt** [comment]
Hello Stefan, 

yes, the fix is also successful on my application. It runs now stable and continuosly for more than an hour. 

Thank you very much for your fast response! 

Best regards, Andi

**Comment by spacehuhn** [comment]
No problem, glad it works now!

**Comment by fermuch** [comment]
Thanks for finding and fixing this bug. I was trying to find if there was a problem at my code for hours, until I decided the check all of my dependencies changelog.

Thanks!!
