### ISSUE TITLE
Using SimpleCLI in Platform IO

### ISSUE THREAD

**Issue by aerlaut** [spacehuhn/SimpleCLI#3]
I'm trying to use SimpleCLI in PlatformIO.

As per instruction, I downloaded the SimpleCLI source files and put it under a "SimpleCLI" in the "libs" folder. I then inserted the library by inserting `#include <SimpleCLI.h>` at the top of `main.cpp`.

The library files compiled sucessfully, but there are linking "undefined reference" errors. I might miss some build configurations under `platformio.ini`. I've tried using the option `lib_ldf_mode = chain+` and `lib_ldf_mode = deep+`, but the linker still fails.

Any idea?

**Comment by tablatronix** [comment]
Do you have more information, logs, what are you compiling for?

**Comment by tablatronix** [comment]
maybe use `lib_extra_dirs` to see if it is a path issue with default lib and include paths ?

**Comment by gloglas** [comment]
Try installing it from the PlatformIO's library manager. That should work as a workaround.

**Comment by aerlaut** [comment]
I didn't realize SimpleCLI is registered in the PlatformIO library. Followed @gloglas's recommendation and installed from the library. Works perfectly and no link errors.
