### ISSUE TITLE
How to implement a set command for more than one setting

### ISSUE THREAD

**Issue by jaccobezemer** [spacehuhn/SimpleCLI#6]
Hi,
I'm trying to implement a set command that can have multiple arguments. Like,
set -auto <on/off>
set -interval <number>
set -devicename <name>
set -trigger <name> -lowtemp 20 -hightemp 40 -speed 33

Is this possible with SimpleCLI? And how?
I suppose this is were addBoundlessCommand is for since I can't get it to work with addArgument and addPositionalArgument.

Kind regards,
Jacco

**Comment by spacehuhn** [comment]
What's the problem you're having with addArgument and addPositionalArgument?

**Comment by jaccobezemer** [comment]
I'm having trouble constructing the correct command and argument set.

How do i add -auto and -interval to the same command without having to input both?

This:
  cmdSet = cli.addCmd("set", onCmdSet);
  cmdSet.addArg("auto");
  cmdSet.addArg("interval");

Gives me the following error:
ERROR: Missing argument at command 'set' at argument '-interval <value>'
Did you mean "set -auto <on> -interval <value>"? 

However, when i use this:
  cmdSet = cli.addCmd("set", onCmdSet);
  cmdSet.addPosArg("setting");
  cmdSet.addPosArg("value");

That gives me a good result.

Is that the way to go? Or is there a better/smarter way?

Thanks

**Comment by spacehuhn** [comment]
Your approach is a bit confusing to me.
You're trying to implement one command that fits all your needs and that's complicated.
But what you really want to do is implement multiple, different commands and name them all `set`, because that should be possible. (Although I wouldn't recommend calling them all the same)

For example:  

`set -auto <on/off>`  

```
cmdSetAuto = cli.addCmd("set", onCmdSet);
cmdSetAuto .addArg("auto");
```  

`set -trigger -lowtemp 20 -hightemp 40 -speed 33`    

```
cmdSetTemp = cli.addCmd("set", onCmdSet);
cmdSetTemp.addFlagArg("trigger ");
cmdSetTemp.addArg("lowtemp","20");
cmdSetTemp.addArg("hightemp","40");
cmdSetTemp.addArg("speed","33");
```

**Comment by jaccobezemer** [comment]
Well this is not the only command. I got more;-)
I got inspired by powershell and other CLI's like Cisco (ios) networking devices. They have commands like show interface, show config, show ip route, show version.
Thanks for your examples.
