### ISSUE TITLE
Tips how to reduce RAM. 

### ISSUE THREAD

**Issue by ami2go** [spacehuhn/SimpleCLI#8]
Hi. 
I recently used your library and thanks for sharing. 
Unfortunately all text variable like below consume a lot of RAM. 
` cmdPing.setDescription(" Responds with a ping n-times");`
I'm using UNO and quickly got run out of RAM. 
One variant i found it working is to store all strings in FLASH:
 ```
 const static char StrInFlash[] PROGMEM = " Responds with a ping n-times"; 
 cmdPing.setDescription(StrInFlash);  
```
if you have just some text to print over Serial you may use directives `Serial.print(F("some text")); `
Here is error callback function modified to use less RAM 
```
void errorCallback(cmd_error* e) {
    CommandError cmdError(e); // Create wrapper object

    Serial.print(F("ERROR: "));
    Serial.println(cmdError.toString());

    if (cmdError.hasCommand()) {
        Serial.print(F("Did you mean \""));
        Serial.print(cmdError.getCommand().toString());
        Serial.println(F("\"?"));
    }
};
```

I hope someone will found it useful too

**Comment by spacehuhn** [comment]
Thanks for the great tip!

I would just like to add a note that this trick might not work on all boards, as Arduino cores differ depending on the chip's architecture.
As already mentioned in the [README](https://github.com/spacehuhn/SimpleCLI#supported-devices), I would generally advice not to use something like the Arduino UNO, as it has not enough memory to store and handle lots of long strings. But if you keep your project small and use tricks like this, you're safe to use it anyway :)

**Comment by Cregrant** [comment]
I don’t see any size changes with the latest PlatformIO and ESP32 (which uses -Os by default).
