### ISSUE TITLE
Pass negative values as command argument

### ISSUE THREAD

**Issue by intensite** [spacehuhn/SimpleCLI#9]
I have implemented your wonderful library in my model rocket flight computer and it saved me so much time Thank you!

I have noticed an issue when I send a command in this format:
```SET  SERVO_1_OFFSET -11```

The command is **SET**  and it expects two arguments a setting and a value  (in this case **SERVO_1_OFFSET**  and **-11**)

Everything works just fine when the value is a positive number.  However I also need to pass negative values and in that case the library trows a **Unknown argument error**

Am I doing something wrong or is there a workaround.

Thank you.

**Comment by intensite** [comment]
Classical case of RTFM, I just noticed that it works when the value is sent in double quotes.

**Comment by spacehuhn** [comment]
Glad you found the solution yourself so quickly :)
Just want to add that this is because the library thinks `-11` is an argument name (as those always start with the `-` symbol), but can't find an argument named `-11` in your command. This explains the "Unknown argument error".
